### ISSUE TITLE
E-mail mező fölötti szöveg > mező alá

### ISSUE THREAD

**Issue by bence002** [Krishtof/booked4us#14]
**Így:**
```
font-family: "Myriad_regular";
font-size: 16px;
font-size: 1.0rem;
color: #263345;
/*font-weight: bolder;*/
font-style: italic;
/* font-weight: 400; */
line-height: 23px;
```
**Ehelyett:**

![kepernyofoto 2016-05-02 - 18 35 18](https://cloud.githubusercontent.com/assets/19146000/14960513/4b5d047a-1095-11e6-89aa-929a97e36bfe.png)

**Comment by Krishtof** [comment]
Ezt kérlek fejtsd ki, nem értem :)

**Comment by bence002** [comment]
**Ehelyett:**
![kepernyofoto 2016-05-02 - 18 35 18](https://cloud.githubusercontent.com/assets/19146000/14980735/c681342e-112a-11e6-8181-d7921056947b.png)

**Valahogy így:**
![kepernyofoto 2016-05-03 - 12 29 38](https://cloud.githubusercontent.com/assets/19146000/14980740/ce44f8e4-112a-11e6-8bf8-ea84a38abe5f.png)

**Comment by Krishtof** [comment]
ok, de ezt hátrateszem, egyelőre a hibákra fokuszálok, meg arra h legyen kinn egy működőképes verzió

**Comment by Krishtof** [comment]
Rájöttem h ez tuti nem jó, mert ott jelenik meg  a hibaüzenet. Attól eltekintve h az eredeti jóval hangsúlyosabb
