### ISSUE TITLE
Full HD és Retina képek aloldalakon

### ISSUE THREAD

**Issue by bence002** [Krishtof/booked4us#23]
Full HD monitorokon vagy Mac Retina kijelzőn az aloldalak betöltődésekor túl nagy helyet foglal el a kép feleslegesen. Légyszi oldd meg Kristóf, hogy kisebb helyet foglaljon a kép sáv
- csapat oldalon látszódjon az első sor fej:
![image](https://cloud.githubusercontent.com/assets/19146000/15039154/b8566186-12aa-11e6-930b-0d6d46c97028.png)

- árak oldalon látszódjon a funkciók eleje:
![image2](https://cloud.githubusercontent.com/assets/19146000/15039250/d3d91402-12ab-11e6-881a-2af0f5afe21b.png)

(köszi @nagybalazs)

**Comment by Krishtof** [comment]
nézd meg a csapatnál, ott sztem ez a méret teljesen jó, és ha valami értelmes képet tudnánk találni a pricinghoz, ott is jó lenne

**Comment by bence002** [comment]
- fullHD, retina, mobil most tökéletes
- csapatnál most sima HD monitoron csak a fejek látszanak, de ha @Krishtof szerinted nem para, akkor felőlem OK:

![kepernyofoto 2016-05-05 - 15 23 32](https://cloud.githubusercontent.com/assets/19146000/15044638/477cb1fa-12d6-11e6-9b02-0b8f6aac90b6.png)
