### ISSUE TITLE
Footer menü reszponzív

### ISSUE THREAD

**Issue by bence002** [Krishtof/booked4us#8]
A footer menü akkor tűnjön el, ha a szendvics menü megjelenik a headerben. Valamelyik a kettő közül mindig látszódjon

**Comment by Krishtof** [comment]
most így van

**Comment by bence002** [comment]
Nem, 1170-nél eltűnik a footer menü és csak 768-nál lesz szendvics. De nem is ez a lényeg, hanem hogy látszódjon légyszi az alsó menüsor is valahogyan mobil eszközökön :)
